### ISSUE TITLE
Unraid install

### ISSUE THREAD

**Issue by guim31** [cidrblock/home_journal#20]
Hi ! Congrats for your work, I'm happy someone with dev skills made a project like this, I was looking for it for ages ! 

Would it be possible to create an Unraid template ?
It would be really helpfull for me (and probably for a lot of people using Unraid !)

**Comment by cidrblock** [comment]
Hey @guim31 

I know very little about unraid and don't use it. Although I do think it would be cool to have it I'm not sure I'm the right one to do it. 

If you go down that road or someone else and have question about running this in a container, feel free to ask, I'm happy to help there.
